services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      backend:
        aliases:
          - mongo
    volumes:
      - mongo_db:/data/db
    env_file:
      - config.env
    profiles:
      - dev
      - prod

  prod:
    image: ${IMAGE_NAME:-myimage:latest}
    restart: always
    ports:
      - 3000:3000
    networks:
      backend:
        aliases:
          - app
    env_file:
      - config.env
    depends_on:
      - mongo_db
    profiles:
      - prod

  dev:
    image: node:18-alpine
    restart: unless-stopped
    working_dir: /app
    command: [ "npm", "run", "start:dev" ]
    ports:
      - 3000:3000
    networks:
      backend:
        aliases:
          - app
    env_file:
      - config.env
    depends_on:
      - mongo_db
    volumes:
      - ${PWD}:/app:rw
    profiles:
      - dev

volumes:
  mongo_db: {}

networks:
  backend: